language: erlang

# install the latest stable rebar
before_install:
   - wget https://github.com/rebar/rebar/wiki/rebar
   - chmod +x rebar

script: "./.travis-ci.sh"
otp_release:
   - 19.3
   - 18.3
   - 17.5
   - R16B03-1
   - R16B01
