language: erlang

# install the latest stable rebar
before_install:
   - wget https://github.com/rebar/rebar/wiki/rebar
   - chmod +x rebar

script: "./.travis-ci.sh"
otp_release:
   - 17.3
   - R16B03-1
   - R16B03
   - R16B02
   - R16B01
   - R15B03
   - R15B02
   - R15B01
   - R14B04
   - R14B03
   - R14B02
